# Generated by Django 5.0.4 on 2024-05-02 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdMPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('display_name', models.CharField(max_length=100, null=True)),
                ('sam_account_name', models.CharField(max_length=100, null=True)),
                ('email_address', models.CharField(max_length=100, null=True)),
                ('account_status', models.CharField(max_length=100, null=True)),
                ('initials', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'AdMPReport',
                'verbose_name_plural': 'AdMPReports',
            },
        ),
        migrations.CreateModel(
            name='TemporaireDRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('matrh', models.CharField(max_length=50)),
                ('logon_name', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('datefin', models.DateField()),
                ('manager', models.CharField(max_length=100)),
                ('hierarchie', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TemporaireDRH',
                'verbose_name_plural': 'TemporairesDRH',
            },
        ),
    ]
