# Generated by Django 5.0.4 on 2024-05-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRBT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('role_id', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=100, null=True)),
                ('email_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'CRBT',
                'verbose_name_plural': 'CRBTs',
            },
        ),
    ]
