# Generated by Django 5.0.4 on 2024-06-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_extraction_user_pretups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='last_login_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
