# Generated by Django 5.0.4 on 2024-06-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_extraction_user_pretups_last_login_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='created_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='last_login_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='modified_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
