# Generated by Django 5.0.4 on 2024-06-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_extraction_user_pretups_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='msisdn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extraction_user_pretups',
            name='pswd_modified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
