# Generated by Django 5.0.4 on 2024-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_extraction_user_pretups_category_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte_users_deleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
